# Generated by Django 3.0.14 on 2023-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stguhclockindicatorsgroup',
            name='group_type',
            field=models.SmallIntegerField(choices=[(1, 'Input/Processes'), (2, 'Outputs'), (3, 'Outcomes'), (4, 'Impacts')], default=1, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='stguhclockindicatorsgrouptranslation',
            name='name',
            field=models.CharField(default='Day [Health Impact and Outcome]', max_length=230, verbose_name='Reference Name'),
        ),
    ]
