# Generated by Django 3.0.14 on 2023-12-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0002_auto_20231209_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stguhclockindicatorsgroup',
            name='group_type',
        ),
    ]
