# Generated by Django 3.0.14 on 2023-12-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '__first__'),
        ('uhc_clock', '0003_remove_stguhclockindicatorsgroup_group_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgUHClockIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indicator_type', models.SmallIntegerField(choices=[(1, 'Input'), (2, 'Process'), (3, 'Output'), (4, 'Outcome'), (5, 'Impact')], default=1, verbose_name='Indicator Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHClockIndicatorsGroup', verbose_name='Indicator Group')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
            ],
        ),
    ]
