# Generated by Django 3.0.14 on 2023-12-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0004_stguhclockindicators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stguhclockindicators',
            options={'managed': True, 'ordering': ('indicator',), 'verbose_name': 'UHC Indicator', 'verbose_name_plural': 'UHC Indicators'},
        ),
        migrations.AlterModelTable(
            name='stguhclockindicators',
            table='stg_uhclock_indicators',
        ),
    ]
