# Generated by Django 3.0.14 on 2023-12-09 17:45

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0005_auto_20231209_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgUHCIndicatorTheme',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2')], default=1, verbose_name='Theme Level')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicators', models.ManyToManyField(blank=True, db_table='stg_uhclock_theme_members', to='uhc_clock.StgUHClockIndicators', verbose_name='Indicators')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHCIndicatorTheme', verbose_name='Parent UHC Theme')),
            ],
            options={
                'verbose_name': 'UHC Theme',
                'verbose_name_plural': ' UHC Themes',
                'db_table': 'stg_uhclock_indicator_themes',
                'ordering': ('level',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgUHCIndicatorThemeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Theme Name')),
                ('shortname', models.CharField(max_length=45, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='uhc_clock.StgUHCIndicatorTheme')),
            ],
            options={
                'verbose_name': 'UHC Theme Translation',
                'db_table': 'stg_uhclock_indicator_themes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
