# Generated by Django 3.0.14 on 2023-12-09 18:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0006_stguhcindicatortheme_stguhcindicatorthemetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stguhcindicatortheme',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHClockIndicatorsGroup', verbose_name='Indicator Group'),
        ),
        migrations.AlterField(
            model_name='stguhcindicatortheme',
            name='indicators',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='group', chained_model_field='indicator', horizontal=True, to='uhc_clock.StgUHClockIndicators'),
        ),
    ]
