# Generated by Django 3.0.14 on 2023-12-10 14:23

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('uhc_clock', '0007_auto_20231209_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts_UHC_DatabaseView',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_id', models.PositiveIntegerField(blank=True, verbose_name='Indicator ID')),
                ('afrocode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Indicator Code')),
                ('indicator', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indicator Name')),
                ('location', models.CharField(max_length=500, verbose_name='Location Name')),
                ('categoryoption', models.CharField(max_length=500, verbose_name='Disaggregation Options')),
                ('datasource', models.CharField(max_length=500, verbose_name='Data Source')),
                ('measure_type', models.CharField(max_length=500, verbose_name='Measure Type')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value')),
                ('start_period', models.PositiveIntegerField(blank=True, verbose_name='Start Year')),
                ('end_period', models.PositiveIntegerField(blank=True, verbose_name='End Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(blank=True, max_length=25, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'UHC Fact',
                'verbose_name_plural': ' UHC-Clock Facts',
                'db_table': 'vw_uhc_fact_data_indicators',
                'ordering': ('indicator',),
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='stguhcindicatortheme',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uhc_clock.StgUHClockIndicatorsGroup', verbose_name='UHC Indicator Group'),
        ),
        migrations.AlterField(
            model_name='stguhcindicatortheme',
            name='indicators',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='group', chained_model_field='group', horizontal=True, to='uhc_clock.StgUHClockIndicators'),
        ),
        migrations.AlterField(
            model_name='stguhclockindicators',
            name='Indicator_type',
            field=models.CharField(choices=[('1', 'Input'), ('2', 'Process'), ('3', 'Output'), ('4', 'Outcome'), ('5', 'Impact')], default='1', max_length=5, verbose_name='Indicator Type'),
        ),
    ]
