# Generated by Django 3.0.14 on 2023-12-12 07:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '__first__'),
        ('uhc_clock', '0008_auto_20231210_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stguhcindicatortheme',
            name='indicators',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='group', chained_model_field='group', horizontal=True, to='uhc_clock.StgUHClockIndicators', verbose_name='indicators'),
        ),
        migrations.AlterField(
            model_name='stguhclockindicators',
            name='Indicator_type',
            field=models.CharField(choices=[('1', 'Input'), ('2', 'Process'), ('3', 'Output'), ('4', 'Outcomes'), ('5', 'Impact')], default='1', max_length=5, verbose_name='Indicator Type'),
        ),
        migrations.CreateModel(
            name='CountrySelectionUHCIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ManyToManyField(default=None, to='uhc_clock.StgUHCIndicatorTheme', verbose_name='UHC Theme')),
                ('indicators', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='domain', chained_model_field='indicator_id', horizontal=True, null=True, to='uhc_clock.StgUHClockIndicators')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Country/Location')),
            ],
            options={
                'verbose_name': 'Country UHC Indicator ',
                'verbose_name_plural': ' Country UHC Indicators',
                'db_table': 'stg_country_uhc_clock_indicators',
                'ordering': ('location',),
                'managed': True,
            },
        ),
    ]
