# Generated by Django 3.0.14 on 2023-12-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '__first__'),
        ('uhc_clock', '0009_auto_20231214_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryselectionuhcindicators',
            options={'managed': True, 'ordering': ('location',), 'verbose_name': 'Country Selection', 'verbose_name_plural': 'UHC Clock Country Selections'},
        ),
        migrations.AlterModelOptions(
            name='facts_uhc_databaseview',
            options={'managed': False, 'ordering': ('indicator',), 'verbose_name': 'UHC Clock Fact', 'verbose_name_plural': '   UHC Clock Facts'},
        ),
        migrations.AlterModelOptions(
            name='stguhclockindicators',
            options={'managed': True, 'ordering': ('indicator',), 'verbose_name': 'UHC Clock Indicator', 'verbose_name_plural': '   UHC Clock Indicators'},
        ),
        migrations.AlterModelOptions(
            name='stguhclockindicatorsgroup',
            options={'managed': True, 'ordering': ('translations__name',), 'verbose_name': 'UHC Clock Indicator Group', 'verbose_name_plural': '  UHC Clock Indicator Groups'},
        ),
        migrations.AlterModelOptions(
            name='stguhclockindicatorsgrouptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'UHC Clock Indicator Group Translation'},
        ),
        migrations.AlterField(
            model_name='stguhclockindicators',
            name='indicator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name'),
        ),
    ]
